version : "3.8"

services:
  prod_redis_cache:
    container_name: prod_redis_cache
    image: redis:alpine3.18
    ports:
      - ${PROD_REDIS_PORT}:${PROD_REDIS_PORT}
    restart: on-failure
    command: redis-server --requirepass ${PROD_REDIS_PASSWORD}
    networks:
      - app_net

  prod_db:
    container_name: prod_postgres_db
    image: postgres:12.16
    ports:
      - ${PROD_POSTGRES_PORT}:${PROD_POSTGRES_PORT}
    restart: on-failure
    volumes:
      - ../prod_data/db:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_DB=${PROD_POSTGRES_DB}
      - POSTGRES_USER=${PROD_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PROD_POSTGRES_PASSWORD}
    networks:
      - app_net

  prod_app:
    container_name: prod_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    networks:
      - app_net
    depends_on:
      - prod_redis_cache
      - prod_db

  nginx:
    container_name: prod_nginx
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net
    depends_on:
      - prod_app

networks:
  app_net: