import { createSlice } from "@reduxjs/toolkit";

// Define the initial state shape using TypeScript interface
interface InitialState {
  userDetails: {
    name: string;
    phoneNumber: string;
    username: string;
    email: string;
    dob: string;
  };
  showSuccess: boolean;
}

// Initialize the state with default values
const initialState: InitialState = {
  userDetails: {
    name: "",
    phoneNumber: "",
    username: "",
    email: "",
    dob: "",
  },
  showSuccess: false,
};

// Create a Redux Toolkit slice
export const userSlice = createSlice({
  name: "user", // Name of the slice
  initialState, // Initial state
  reducers: {
    // Action to set user details in the state
    setUserDetails(state, action) {
      state.userDetails = action.payload;
    },
    // Action to set the showSuccess flag in the state
    setShowSuccess(state, action) {
      state.showSuccess = action.payload;
    },
  },
});

// Export action creators
export const { setUserDetails, setShowSuccess } = userSlice.actions;

// Export the reducer function generated by createSlice
export default userSlice.reducer;
